name: handbrake
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  auto_route: ^10.1.0+1
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  freezed: ^3.1.0
  freezed_annotation: ^3.1.0
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  bloc: ^9.0.0
  google_fonts: ^6.2.1
  flutter_bloc: ^9.1.1
  path: ^1.9.1
  another_flutter_splash_screen: ^1.2.1
  easy_date_timeline: ^2.0.9
  intl: ^0.20.2
  table_calendar: ^3.2.0
  sqlite3_flutter_libs: ^0.5.37
  collection: ^1.19.1
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  auto_route_generator: ^10.1.0
  drift_dev: ^2.27.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
